In [1]:
import pandas as pd

In [95]:
import numpy as np

In [34]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")

## Question 1 

In [35]:
pd.__version__

'2.3.1'

## Question 2

In [130]:
len(df)

9704

In [37]:
df.size

106744

## Question 3 

In [38]:
df.nunique()

engine_displacement      36
num_cylinders            14
horsepower              192
vehicle_weight         9704
acceleration            162
model_year               24
origin                    3
fuel_type                 2
drivetrain                2
num_doors                 9
fuel_efficiency_mpg    9704
dtype: int64

## Question 4 

In [39]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

## Question 5

In [40]:
df.fuel_efficiency_mpg.max()

25.96722204888372

## Question 6

In [41]:
oldmedian = df.horsepower.median()

In [42]:
oldmedian

149.0

In [59]:
frequent_val = df.horsepower.mode()

In [68]:
frequent_val = int(frequent_val[0])

In [45]:
df['horsepower'] = df['horsepower'].fillna(frequent_val)

In [50]:
df.isna().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [70]:
df['horsepower'] = df['horsepower'].fillna(frequent_val)

In [71]:
newmedian = df.horsepower.median()

In [72]:
newmedian

152.0

## Question 7

In [115]:
X = df.loc[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7).to_numpy()

In [116]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [117]:
XT = X.T

In [121]:
XTX = np.dot(XT, X)

In [122]:
XTX

array([[62248334.33150762, 41431216.50732678],
       [41431216.50732678, 28373339.        ]])

In [123]:
XTX = np.linalg.inv(XTX)

In [124]:
XTX

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [125]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [127]:
w = np.dot(np.dot(XTX, XT),y)

In [128]:
w

array([0.01386421, 0.5049067 ])

In [129]:
np.sum(w)

np.float64(0.5187709081074007)