In [1]:
import numpy as np 

In [2]:
np

<module 'numpy' from 'C:\\Users\\Ziyi\\anaconda3\\envs\\mlzoomcamp\\Lib\\site-packages\\numpy\\__init__.py'>

In [4]:
np.zeros(4)

array([0., 0., 0., 0.])

In [5]:
np.ones(4)

array([1., 1., 1., 1.])

In [6]:
np.full(4, 2.5)

array([2.5, 2.5, 2.5, 2.5])

In [7]:
li = [1,2,3,4]

In [11]:
a = np.array(li)

In [15]:
a[2]

np.int64(3)

In [17]:
print(a[2])

3


In [18]:
a[2] +2 

np.int64(5)

In [19]:
a[2] = 10

In [20]:
a

array([ 1,  2, 10,  4])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [25]:
range(3,10)

range(3, 10)

In [30]:
np.linspace(0, 10, 5) #from 1to 10. with 5 elements

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [32]:
np.zeros((5,2)) #5*2 

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
np.array([
    [1,2,3],
    [4,5,6]
    
])

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
n = np.array([
    [1,2,3],
    [4,5,6]
    
])

In [37]:
n[0,0]

np.int64(1)

In [38]:
n[1,1] =20

In [39]:
n

array([[ 1,  2,  3],
       [ 4, 20,  6]])

In [40]:
n[0]

array([1, 2, 3])

In [41]:
n[1] = [5,5,5]

In [42]:
n

array([[1, 2, 3],
       [5, 5, 5]])

In [44]:
n[:,1]

array([2, 5])

In [45]:
n[:,1] = [10,10]

In [46]:
n

array([[ 1, 10,  3],
       [ 5, 10,  5]])

In [47]:
## Randomly generated arrays 

In [52]:
np.random.seed(2) #once set the seed, everytime it will generate the same array
np.random.rand(5,2) #uniform distributed

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [53]:
np.random.seed(2) 
np.random.randn(5,2) #normal distribution 

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [54]:
100 * np.random.randn(5,2)

array([[  55.14540445,  229.22080128],
       [   4.1539393 , -111.79254451],
       [  53.90583206,  -59.61596998],
       [  -1.91304965,  117.50012195],
       [ -74.78709493,    0.9025251 ]])

In [56]:
np.random.randint(low = 0, high = 100, size = (5,2))

array([[83, 31],
       [66, 80],
       [52, 76],
       [50,  4],
       [90, 63]], dtype=int32)

In [57]:
## element-wise operations

In [60]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [61]:
a +1

array([1, 2, 3, 4, 5])

In [62]:
a * 2

array([0, 2, 4, 6, 8])

In [64]:
b = 10 + (a /2)

In [65]:
a + b

array([10. , 11.5, 13. , 14.5, 16. ])

In [66]:
a *b

array([ 0. , 10.5, 22. , 34.5, 48. ])

In [67]:
a 

array([0, 1, 2, 3, 4])

In [68]:
a >= 2 

array([False, False,  True,  True,  True])

In [69]:
a > b

array([False, False, False, False, False])

In [72]:
a[a >= 2] #returns the elements values not index

array([2, 3, 4])

In [73]:
a.min()

np.int64(0)

In [74]:
a.sum()

np.int64(10)

In [75]:
a.std()

np.float64(1.4142135623730951)

In [76]:
n.sum()

np.int64(34)